### ISSUE TITLE
Prefix lookups possible?

### ISSUE THREAD

**Issue by eliaswendt** [zeek/pysubnettree#21] opened 2020-06-23 18:04 UTC
Hi there,

I was just wondering, whether it's also possible to directly lookup prefixes (instead of IPs) in the SubnetTree.
I tried the following:

```python
from SubnetTree import SubnetTree

subnet_tree = SubnetTree()

subnet_tree['10.0.0.0/24'] = "/24"
subnet_tree['10.0.0.0/25'] = "/25"

print(subnet_tree['10.0.0.0/24'])
```

As output I received: "/25"

I am wondering what happens here, as I expected "/24" as result.
First idea that came to my mind, was, that the lookup (last line) just cuts-off the trailing "/24" and uses the prefix as IP, which would match the /25 (longest prefix). Otherwise, may this be a bug?

EDIT: I am using version 0.33 with Python 3.8.1 on macOS

**Comment by 0xxon** [comment] 2020-06-23 21:16
I think this is a duplicate of #16 

In that @jsiwek indicated that no, it currently is not possible to do a direct prefix lookup. Though you can get a list of the prefixes.

Closing this as a duplicate.

**Closed by 0xxon** 2020-06-23 21:16 UTC
